#!/bin/bash

if $1 ; then
	echo "writing: $1"
else
	echo "please enter a string"
fi

USERS=`w | grep -Eo "^\w+" | grep -vE '(jcaven|USER)' | uniq`
for u in $USERS; do
	./random_cow.py "$1" # | write $u

done



